# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'og-bomber-gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import bombDriver as d
import webbrowser
from PyQt5 import QtCore, QtGui, QtWidgets
import getpass
import time
import json
import setup
un=getpass.getuser()
class Ui_OgBomber(object):
    def setupUi(self, OgBomber):
        OgBomber.setObjectName("OgBomber")
        OgBomber.resize(800, 600)
        OgBomber.setStyleSheet("QTabWidget{\n"
"background-color: rgb(40, 40, 40);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(OgBomber)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Bomb = QtWidgets.QWidget()
        self.Bomb.setStyleSheet("QWidget{\n"
"background-color: rgb(49, 49, 49);\n"
"}")
        self.Bomb.setObjectName("Bomb")
        self.label = QtWidgets.QLabel(self.Bomb)
        self.label.setGeometry(QtCore.QRect(200, 20, 396, 104))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Most Wazted")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.Bomb)
        self.label_10.setGeometry(QtCore.QRect(60, 144, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Futura Md BT")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Bomb)
        self.label_11.setGeometry(QtCore.QRect(190, 200, 131, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_11.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.username_2 = QtWidgets.QLineEdit(self.Bomb)
        self.username_2.setGeometry(QtCore.QRect(410, 200, 201, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(18)
        self.username_2.setFont(font)
        self.username_2.setAcceptDrops(True)
        self.username_2.setStyleSheet("QLineEdit{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.username_2.setObjectName("username_2")
        self.line_2 = QtWidgets.QFrame(self.Bomb)
        self.line_2.setGeometry(QtCore.QRect(60, 170, 681, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line_2.setPalette(palette)
        self.line_2.setStyleSheet("Line{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.cc = QtWidgets.QComboBox(self.Bomb)
        self.cc.setGeometry(QtCore.QRect(340, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        self.cc.setFont(font)
        self.cc.setAutoFillBackground(False)
        self.cc.setStyleSheet("QComboBox{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.cc.setObjectName("cc")
        self.cc.addItem("")
        self.cc.addItem("")
        self.cc.addItem("")
        self.label_12 = QtWidgets.QLabel(self.Bomb)
        self.label_12.setGeometry(QtCore.QRect(180, 250, 141, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.username_3 = QtWidgets.QLineEdit(self.Bomb)
        self.username_3.setGeometry(QtCore.QRect(340, 250, 61, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(18)
        self.username_3.setFont(font)
        self.username_3.setAcceptDrops(True)
        self.username_3.setStyleSheet("QLineEdit{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.username_3.setObjectName("username_3")
        self.label_13 = QtWidgets.QLabel(self.Bomb)
        self.label_13.setGeometry(QtCore.QRect(180, 300, 141, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.t = QtWidgets.QComboBox(self.Bomb)
        self.t.setGeometry(QtCore.QRect(340, 300, 51, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        self.t.setFont(font)
        self.t.setAutoFillBackground(False)
        self.t.setStyleSheet("QComboBox{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.t.setObjectName("t")
        self.t.addItem("")
        self.t.addItem("")
        self.t.addItem("")
        self.t.addItem("")
        self.bomb = QtWidgets.QPushButton(self.Bomb)
        self.bomb.setGeometry(QtCore.QRect(340, 360, 131, 31))
        self.bomb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bomb.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(170, 255, 0);\n"
"color: rgb(170, 255, 0);\n"
"background-color: rgb(49, 49, 49);\n"
"font-weight: bold;\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 255, 0);\n"
"color: rgb(49, 49, 49);\n"
"}")
        self.bomb.setObjectName("bomb")
        self.bomb.clicked.connect(self.call_bomb)
        self.label_14 = QtWidgets.QLabel(self.Bomb)
        self.label_14.setGeometry(QtCore.QRect(490, 130, 211, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_14.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Blancha")
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Bomb)
        self.label_15.setGeometry(QtCore.QRect(360, 550, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"color:rgb(170, 255, 0);\n"
"}")
        self.label_15.setObjectName("label_15")
        self.progressBar = QtWidgets.QProgressBar(self.Bomb)
        self.progressBar.setGeometry(QtCore.QRect(330, 430, 211, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"color: rgb(170, 255, 0);\n"
"background-color: rgb(49, 49, 49);\n"
"border: 2px solid rgb(170, 255, 0);\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.label_17 = QtWidgets.QLabel(self.Bomb)
        self.label_17.setGeometry(QtCore.QRect(240, 420, 81, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.Bomb, "")
        self.about = QtWidgets.QWidget()
        self.about.setStyleSheet("QWidget{\n"
"background-color: rgb(49, 49, 49);\n"
"}")
        self.about.setObjectName("about")
        self.label_6 = QtWidgets.QLabel(self.about)
        self.label_6.setGeometry(QtCore.QRect(60, 280, 131, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_6.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.about)
        self.line.setGeometry(QtCore.QRect(60, 126, 681, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.line.setPalette(palette)
        self.line.setStyleSheet("Line{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.about)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.about)
        self.label_4.setGeometry(QtCore.QRect(53, 200, 131, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.about)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 161, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.about)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Futura Md BT")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.about)
        self.label_7.setGeometry(QtCore.QRect(300, 20, 211, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Most Wazted")
        font.setPointSize(36)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.about)
        self.label_8.setGeometry(QtCore.QRect(250, 330, 331, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 49, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Blancha")
        font.setPointSize(36)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"color: rgb(170, 255, 0);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.github = QtWidgets.QPushButton(self.about)
        self.github.setGeometry(QtCore.QRect(250, 450, 91, 23))
        self.github.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(170, 255, 0);\n"
"color: rgb(170, 255, 0);\n"
"background-color: rgb(49, 49, 49);\n"
"font-weight: bold;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 255, 0);\n"
"color: rgb(49, 49, 49);\n"
"}")
        self.github.setObjectName("github")
        self.github.clicked.connect(self.openGithub)
        self.github_2 = QtWidgets.QPushButton(self.about)
        self.github_2.setGeometry(QtCore.QRect(490, 450, 91, 23))
        self.github_2.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(170, 255, 0);\n"
"color: rgb(170, 255, 0);\n"
"background-color: rgb(49, 49, 49);\n"
"font-weight: bold;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 255, 0);\n"
"color: rgb(49, 49, 49);\n"
"}")
        self.github_2.setObjectName("github_2")
        self.github_2.clicked.connect(self.openPaypal)
        self.insta = QtWidgets.QPushButton(self.about)
        self.insta.setGeometry(QtCore.QRect(370, 450, 91, 23))
        self.insta.setStyleSheet("QPushButton{\n"
"border:2px solid rgb(170, 255, 0);\n"
"color: rgb(170, 255, 0);\n"
"background-color: rgb(49, 49, 49);\n"
"font-weight: bold;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 255, 0);\n"
"color: rgb(49, 49, 49);\n"
"}")
        self.insta.setObjectName("insta")
        self.insta.clicked.connect(self.openInsta)
        self.username = QtWidgets.QLineEdit(self.about)
        self.username.setGeometry(QtCore.QRect(200, 160, 201, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(18)
        self.username.setFont(font)
        self.username.setAcceptDrops(True)
        self.username.setStyleSheet("QLineEdit{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.username.setReadOnly(True)
        self.username.setObjectName("username")
        self.userid = QtWidgets.QLineEdit(self.about)
        self.userid.setGeometry(QtCore.QRect(200, 200, 201, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(18)
        self.userid.setFont(font)
        self.userid.setStyleSheet("QLineEdit{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.userid.setReadOnly(True)
        self.userid.setObjectName("userid")
        self.subscription = QtWidgets.QLineEdit(self.about)
        self.subscription.setGeometry(QtCore.QRect(200, 240, 201, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(18)
        self.subscription.setFont(font)
        self.subscription.setStyleSheet("QLineEdit{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.subscription.setReadOnly(True)
        self.subscription.setObjectName("subscription")
        self.smslimit = QtWidgets.QLineEdit(self.about)
        self.smslimit.setGeometry(QtCore.QRect(200, 280, 201, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Light")
        font.setPointSize(18)
        self.smslimit.setFont(font)
        self.smslimit.setStyleSheet("QLineEdit{\n"
"color: rgb(170, 255, 0);\n"
"border: 1px solid rgb(170, 255, 0);\n"
"}")
        self.smslimit.setReadOnly(True)
        self.smslimit.setObjectName("smslimit")
        self.label_9 = QtWidgets.QLabel(self.about)
        self.label_9.setGeometry(QtCore.QRect(280, 540, 281, 16))
        self.label_9.setStyleSheet("QLabel{\n"
"color:rgb(170, 255, 0);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_16 = QtWidgets.QLabel(self.about)
        self.label_16.setGeometry(QtCore.QRect(280, 510, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"color:rgb(170, 255, 0);\n"
"}")
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.about, "")
        OgBomber.setCentralWidget(self.centralwidget)

        self.retranslateUi(OgBomber)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OgBomber)

    def retranslateUi(self, OgBomber):
        _translate = QtCore.QCoreApplication.translate
        OgBomber.setWindowTitle(_translate("OgBomber", "og-bomber"))
        self.label.setText(_translate("OgBomber", "OG Bomber"))
        self.label_10.setText(_translate("OgBomber", "Send Bomb"))
        self.label_11.setText(_translate("OgBomber", "Phone No. : "))
        self.cc.setItemText(0, _translate("OgBomber", "91"))
        self.cc.setItemText(1, _translate("OgBomber", "95"))
        self.cc.setItemText(2, _translate("OgBomber", "1"))
        self.label_12.setText(_translate("OgBomber", "No. of SMS : "))
        self.label_13.setText(_translate("OgBomber", "Time delay : "))
        self.t.setItemText(0, _translate("OgBomber", "3"))
        self.t.setItemText(1, _translate("OgBomber", "5"))
        self.t.setItemText(2, _translate("OgBomber", "7"))
        self.t.setItemText(3, _translate("OgBomber", "10"))
        self.bomb.setText(_translate("OgBomber", "Start Bombing"))
        self.label_14.setText(_translate("OgBomber", "Developed by Samartha"))
        self.label_15.setText(_translate("OgBomber", "*do not missuse"))
        self.label_17.setText(_translate("OgBomber", "Progress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Bomb), _translate("OgBomber", "Bomb"))
        self.label_6.setText(_translate("OgBomber", "SMS Limit : "))
        self.label_3.setText(_translate("OgBomber", "Username : "))
        self.label_4.setText(_translate("OgBomber", "User ID :"))
        self.label_5.setText(_translate("OgBomber", "Subscription : "))
        self.label_2.setText(_translate("OgBomber", "User Profile"))
        self.label_7.setText(_translate("OgBomber", "OG Bomber"))
        self.label_8.setText(_translate("OgBomber", "Developed by Samartha"))
        self.github.setText(_translate("OgBomber", "Github"))
        self.github_2.setText(_translate("OgBomber", "Donate"))
        self.insta.setText(_translate("OgBomber", "Instagram"))
        self.label_9.setText(_translate("OgBomber", "*Donate and become a premium member *do not missuse"))
        self.label_16.setText(_translate("OgBomber", "*for queries mail me : samarthaog@gmail.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about), _translate("OgBomber", "About"))
        user=d.sendUserInfo(un)
        self.username.setText(user["uname"])
        self.userid.setText(user["uid"])
        self.subscription.setText(user["urole"])
        self.smslimit.setText(user["uquota"])

    def openPaypal(self):
        webbrowser.open('https://paypal.me/samartha890?locale.x=en_GB')
    def openGithub(self):
        webbrowser.open('https://github.com/yunghog')
    def openInsta(self):
        webbrowser.open('https://instagram.com/samartha__')
    def call_bomb(self):
        pn=self.username_2.text()
        cc_=self.cc.currentText()
        un_=un
        n=self.username_3.text()
        d.startBombing(pn,cc_,n,un_)
        m=int(n)
        for i in range(m+1):
            a=(i/m)*100
            self.progressBar.setProperty("value",a)
            time.sleep(1)

from res import style

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OgBOmber = QtWidgets.QMainWindow()
    ui = Ui_OgBomber()
    ui.setupUi(OgBOmber)
    OgBOmber.show()
    sys.exit(app.exec_())
